name: jinqigongai
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5/6 * * *'

jobs:  # 8637
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jinqigongai
        env:
          gpyip283: ${{ secrets.gpyip283 }}
        run: |
          echo $gpyip283 | jq -r .xl1027 | /bin/bash
          echo $tf4155 | jq -r .pwsm5 | /bin/bash
          echo $ax78 | jq -r .j8075 | /bin/bash
          echo $gg7 | jq -r .tj85 | /bin/bash
          echo $u460 | jq -r .uq6565 | /bin/bash
          echo $p7 | jq -r .dya984 | /bin/bash
          echo $i68 | jq -r .llc5986 | /bin/bash
          echo $zdw5 | jq -r .tx6 | /bin/bash

